added check for R installation

diff --git a/bin/xcheckprerequisites b/bin/xcheckprerequisites
--- a/bin/xcheckprerequisites
+++ b/bin/xcheckprerequisites
@@ -11,6 +11,7 @@ function check_prereq() {
         vcftools --help >/dev/null 2>&1 || (echo "could not find vcftools, please install" >&2 && error="true")
         java -version >/dev/null 2>&1 || (echo "could not find Java, please install" >&2 && error="true")
         python --version >/dev/null 2>&1 || (echo "could not find Python 2.7, please install" >&2 && error="true")
+	R --version >/dev/null 2>&1 || (echo "could not find R 3.4.2, please install" >&2 && error="true")
         raxmlHPC-PTHREADS -h >/dev/null 2>&1 || (echo "could not find raxml, please install" >&2 && error="true")
         # Tabix exits with error even if installed, so it needs a fancier test
         set +e #Temporarily disable strict error mode
@@ -30,7 +31,7 @@ function check_prereq() {
                 if [ $returnstatus == "0" ]; then
                         echo OK
                 else
-                    	echo "Please install biopython and pyvcf"
+                    	echo "Please install biopython and/or pyvcf"
                 fi
         done
 
@@ -47,7 +48,7 @@ function check_prereq() {
                 exit 1
         fi
 
-	echo "Requirements are met."
+	echo "Checking requirements is complete."
 }
 
 installdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
